### ISSUE TITLE
Random crash due to EOF

### ISSUE THREAD

**Issue by heuristicus** [strands-project/sensortag#3]
I think it was running for ~30 mins before this happened.

``` sh
Traceback (most recent call last):
  File "/home/strands/tsc_y4_ws/src/sensortag/scripts/sensortagRead.py", line 244, in <module>
    sensortag_measure()
  File "/home/strands/tsc_y4_ws/src/sensortag/scripts/sensortagRead.py", line 154, in sensortag_measure
    msg_t.measurement.data = temperature()
  File "/home/strands/tsc_y4_ws/src/sensortag/scripts/sensortagRead.py", line 50, in temperature
    tag.con.expect('descriptor: .*? \r')  
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7ff7fa086450>
command: /usr/bin/gatttool
args: ['/usr/bin/gatttool', '-b', 'B0:B4:48:BE:CC:06', '--interactive']
buffer (last 100 chars): ''
before (last 100 chars): 'scriptor read failed: Request attribute has encountered an unlikely error\r\n[B0:B4:48:BE:CC:06][LE]> '
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 9918
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
")  0: re.compile("descriptor: .*?
```

**Comment by heuristicus** [comment]
Happened again about 5 minutes ago.

Maybe something to do with the sensor turning off?
